DocWare/Controllers/FolderAndFileController.cs
using DocWare.Helpers;
using DocWare.Models;
using DocWare.Resources;
using Ionic.Zip;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Utility.Helpers;
using Utility.Models;

namespace DocWare.Controllers
{
    [CheckAuthorization]
    public class FolderAndFileController : BaseController
    {
        DBEntities db = new DBEntities();
        DAL objDAL = new DAL();
        List<string> parentLst = new List<string>();

        #region --> Folder Management | Add | Jasmin | 09022018
        [HttpGet, Route("AddFolder")]
        public ActionResult AddFolder(long id = 0, long parentFolderId = 0)
        {
            FolderDetailVM folderDetailVM = new FolderDetailVM();
            try
            {
                using (db = new DBEntities())
                {
                    if (id > 0)
                    {
                        folderDetailVM = db.FolderDetails.Where(j => j.Id == id).Select(j => new FolderDetailVM
                        {
                            Id = j.Id,
                            Name = j.Name,
                            FolAssignFormTemplateId = j.AssignFormTemplateId,
                            FolAssignFormTemplateName = j.AssignFormTemplateId > 0 ? db.AssignFormTemplates.Where(x => x.Id == j.AssignFormTemplateId).FirstOrDefault().FormTitle : string.Empty,
                            Notes = j.Notes,
                            Keywords = j.Keywords
                        }).FirstOrDefault();
                    }

                    if (parentFolderId > 0)
                    {
                        folderDetailVM.ParentFolderId = parentFolderId;
                    }
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            return View(folderDetailVM);
        }

        [HttpGet]
        public JsonResult EditFolder(long id)
        {
            FolderDetailVM folderDetailVM = new FolderDetailVM();
            try
            {
                using (db = new DBEntities())
                {
                    if (id > 0)
                    {
                        folderDetailVM = db.FolderDetails.Where(j => j.Id == id).Select(j => new FolderDetailVM
                        {
                            Id = j.Id,
                            Name = j.Name,
                            FolAssignFormTemplateId = j.AssignFormTemplateId,
                            FolAssignFormTemplateName = j.AssignFormTemplateId > 0 ? db.AssignFormTemplates.Where(x => x.Id == j.AssignFormTemplateId).FirstOrDefault().FormTitle : string.Empty,
                            Notes = j.Notes,
                            Keywords = j.Keywords,
                            ParentFolderId = j.ParentFolderId,
                            Description = j.Description,
                            PhysicalLocation = j.PhysicalLocation,
                            PublicFolder = j.IsPublic
                        }).FirstOrDefault();

                        return Json(new { success = true, folderData = folderDetailVM }, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            catch (Exception e)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, Route("AddFolder")]
        [AuditLog(EnumList.EnumLogType.SaveData, "AddFolder")]
        public ActionResult AddFolder(FolderDetailVM data)
        {
            FolderDetail folderDetail = new FolderDetail();

            try
            {
                long userId = CommonFunctions.GetUserId();
                long CabinetId = CommonFunctions.GetCabinetId();

                using (db = new DBEntities())
                {
                    if (data.Id > 0)
                    {
                        using (var transaction = db.Database.BeginTransaction())
                        {
                            folderDetail = db.FolderDetails.Where(m => m.Id == data.Id).FirstOrDefault();

                            if (data.FolFormTemplateId > 0)
                            {
                                AssignFormTemplate assignFormTemplate = new AssignFormTemplate();
                                FormTemplate formTemplate = new FormTemplate();

                                formTemplate = db.FormTemplates.Where(j => j.Id == data.FolFormTemplateId).FirstOrDefault();

                                if (data.FolAssignFormTemplateId > 0)
                                {
                                    assignFormTemplate = db.AssignFormTemplates.Where(j => j.Id == data.FolAssignFormTemplateId).FirstOrDefault();

                                    assignFormTemplate.FormTitle = formTemplate.FormTitle;
                                    assignFormTemplate.FormContant = formTemplate.HtmlContent;
                                    assignFormTemplate.UpdatedBy = userId.ToString();
                                    assignFormTemplate.UpdatedDate = DateTime.Now;
                                    db.Entry(assignFormTemplate).State = EntityState.Modified;
                                    db.SaveChanges();

                                    var formField = db.AssignedFormControlProperties.Where(j => j.AssignedFormTemplateId == assignFormTemplate.Id).ToList();
                                    if (formField.Count() > 0)
                                    {
                                        db.AssignedFormControlProperties.RemoveRange(formField);
                                        db.SaveChanges();
                                    }

                                    var formFields = db.FormControlProperties.Where(j => j.FormTemplateId == formTemplate.Id).ToList();

                                    if (formFields != null)
                                    {
                                        AssignedFormControlProperty assignedFormControlProperty = new AssignedFormControlProperty();
                                        foreach (var field in formFields)
                                        {
                                            if (field != null)
                                            {
                                                assignedFormControlProperty.AssignedFormTemplateId = assignFormTemplate.Id;
                                                assignedFormControlProperty.FieldId = field.FieldId;
                                                assignedFormControlProperty.FieldType = field.FieldType;
                                                db.AssignedFormControlProperties.Add(assignedFormControlProperty);
                                                db.SaveChanges();
                                            }
                                        }
                                    }
                                }
                                else
                                {
                                    assignFormTemplate.FormTitle = formTemplate.FormTitle;
                                    assignFormTemplate.FormContant = formTemplate.HtmlContent;
                                    assignFormTemplate.CreatedBy = userId.ToString();
                                    assignFormTemplate.CreatedDate = DateTime.Now;
                                    db.AssignFormTemplates.Add(assignFormTemplate);
                                    db.SaveChanges();

                                    data.FolAssignFormTemplateId = assignFormTemplate.Id;

                                    var formFields = db.FormControlProperties.Where(j => j.FormTemplateId == formTemplate.Id).ToList();

                                    if (formFields != null)
                                    {
                                        AssignedFormControlProperty assignedFormControlProperty = new AssignedFormControlProperty();
                                        foreach (var field in formFields)
                                        {
                                            if (field != null)
                                            {
                                                assignedFormControlProperty.AssignedFormTemplateId = assignFormTemplate.Id;
                                                assignedFormControlProperty.FieldId = field.FieldId;
                                                assignedFormControlProperty.FieldType = field.FieldType;
                                                db.AssignedFormControlProperties.Add(assignedFormControlProperty);
                                                db.SaveChanges();
                                            }
                                        }
                                    }
                                }
                            }

                            folderDetail.AssignFormTemplateId = data.FolAssignFormTemplateId;
                            folderDetail.ParentFolderId = data.ParentFolderId;
                            folderDetail.Name = data.Name.Trim();
                            folderDetail.Notes = data.Notes != null ? data.Notes.Trim() : "";
                            folderDetail.Keywords = data.Keywords != null ? data.Keywords : "";
                            folderDetail.Description = data.Description;
                            folderDetail.PhysicalLocation = data.PhysicalLocation;
                            folderDetail.IsPublic = data.PublicFolder;
                            folderDetail.UpdatedBy = userId.ToString();
                            folderDetail.UpdatedDate = DateTime.Now;

DocWare/Views/FolderAndFile/AddFolder.cshtml
@model FolderDetailVM
@{
    ViewBag.Title = Resource.Add_Edit_Folder;
    Layout = "~/Views/Shared/_Layout.cshtml";
    long UserId = CommonFunctions.GetUserId();
    long CabinetId = CommonFunctions.GetCabinetId();
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        @if (Model.Id > 0)
        {
            <h2>@Resource.Edit_Folder</h2>
        }
        else
        {
            <h2>@Resource.Add_Folder</h2>
        }
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("GoToHome", "Account")"><i class="fa fa-lg fa-home"></i></a>
            </li>
            <li>
                <a>@Resource.Folder_Management</a>
            </li>
            <li class="active">
                <strong>
                    @if (Model.Id > 0)
                    {
                        @Model.Name
                    }
                    else
                    {
                        @Resource.Add_Folder
                    }
                </strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    @using (Html.BeginForm("AddFolder", "FolderAndFile", FormMethod.Post, new { @id = "frmAddFolder" }))
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @Html.HiddenFor(j => j.Id)
                                @Html.HiddenFor(j => j.ParentFolderId)
                                @Html.HiddenFor(j => j.FolAssignFormTemplateId)

                                <div class="row">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">@Resource.Name</label>
                                        <div class="col-md-4">
                                            @Html.TextBoxFor(q => q.Name, new { @class = "form-control", @maxlength = "50", @autofocus = "autofocus" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">@Resource.Keywords</label>
                                        <div class="col-md-10">
                                            @Html.TextBoxFor(q => q.Keywords, new { @class = "form-control", @maxlength = "500" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">@Resource.Notes</label>
                                        <div class="col-md-10">
                                            @Html.TextAreaFor(q => q.Notes, new { @class = "form-control", @maxlength = "500" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div id="divAssignFormTemplate">
                                    <div class="row">
                                        <div class="form-group">
                                            <label class="col-md-2 control-label">Assigned Form Template</label>
                                            <div class="col-md-4">
                                                @Html.TextBoxFor(j => j.FolAssignFormTemplateName, new { @class = "form-control", @disabled = "disabled" })
                                            </div>
                                            <div class="col-md-3">
                                                <button type="button" class="btn btn-success" onclick="ShowFormTemplate()">Attach New Form Template</button>
                                            </div>
                                        </div>
                                    </div>
                                    <br />
                                </div>
                                <div class="row" id="divFormTemplate">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">@Resource.Select_FormTemplate</label>
                                        <div class="col-md-4">
                                            @Html.DropDownListFor(j => j.FolFormTemplateId, CommonFunctions.GetFormTemplateList(), new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="pull-right">
                                            <button type="button" id="btnSave" class="btn btn-default">
                                                <i class="fa fa-save text-navy"></i>&nbsp;
                                                @Resource.Save
                                            </button>
                                            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("FolderTreeView")'">
                                                <i class="fa fa-close text-danger"></i>&nbsp;
                                                @Resource.Cancel
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    @Styles.Render("~/plugins/tagInputsStyles")
}

@section Scripts{
    @Scripts.Render("~/plugins/tagInputs")
    <script type="text/javascript">

        $(document).ready(function () {
            if ($("#Id").val() > 0 && $("#FolAssignFormTemplateId").val() > 0) {
                $("#divAssignFormTemplate").show();
                $("#divFormTemplate").hide();
            }
            else {
                $("#divFormTemplate").show();
                $("#divAssignFormTemplate").hide();
            }

            $("#frmAddFolder").validate({
                highlight: function (e) {
                    $(e).closest('.form-group').removeClass('has-success has-error');
                    $(e).closest('.form-group').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    e.closest('.form-group').removeClass('has-success has-error');
                    $(e).prev().removeClass('has-error');
                    e.closest('.help-block').remove();
                    $(e).remove();
                },
                ignore: [],
                rules: {
                    Name: {
                        required: true,
                        remote: {
                            url: '@Url.Action("CheckFolderName", "FolderAndFile")',
                            data: {
                                FolderName: function () { return $("#Name").val(); },
                                FolderID: function () { return $("#Id").val(); },
                            }
                        }
                    },
                    Notes: {
                        required: true,
                    },
                    Keywords: {
                        required: true,
                    }
                },
                messages: {
                    Name: {
                        required: "@Messages.FolderName_Validation",
                        remote: "@Messages.Folder_already_exist"
                    },
                    Notes: {
                        required: "@Messages.Enter_notes",
                    },
                    Keywords: {
                        required: "@Messages.Enter_keywords",
                    }
                },
                errorPlacement: function (error, element) {
                    element.parent().append(error);
                    //error.insertAfter(element.parent("div"));
                }
            });

            $("#btnSave").click(function () {
                if ($("#frmAddFolder").valid()) {
                    $("#frmAddFolder").submit();
                }
                else
                    return false;
            });

            $('#Keywords').change(function () {
                if ($('#Keywords').val() != "") {
                    $("#Keywords").next().css("display", "none");
                    $("#Keywords").closest('.form-group').removeClass('has-error');
                }
            });

            if ($("#Id").val() > 0) {
                $('#Keywords').tagsinput('removeAll');
                $('#Keywords').tagsinput('add', '');
                var dataString = $("#Keywords").val();
                var stringLst = dataString.split(",");
                if (stringLst != undefined) {
                    for (var i = 0; i < stringLst.length; i++) {
                        $('#Keywords').tagsinput("add", stringLst[i]);
                    }
                }
            }

            $('#Keywords').tagsinput({
                tagClass: 'label label-primary'
            });
        });

        function ShowFormTemplate() {
            $("#divFormTemplate").show();
        }
    </script>
}

DocWare/Views/FolderAndFile/FolderTreeView.cshtml
@{
    ViewBag.Title = Resource.Folder_Management;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <h2>@Resource.Folder_Management</h2>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="col-lg-6">
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-lg-6">
                                <a href="javascript:void(0)" onclick="folderDetails(0)"><i class="fa fa-lg fa-server"></i> @ViewBag.CabinetName</a>
                            </div>
                            <div class="form-group col-lg-6">
                                <div class="input-group">
                                    <input type="text" id="SearchFolderName" class="form-control" placeholder="Folder Name">
                                    <span class="input-group-btn">
                                        <button type="button" id="btnSearchFolder" class="btn btn-primary">
                                            Go!
                                        </button>
                                    </span>
                                </div>
                                <label id="SearchFolderName-error" class="error has-error">Enter folder name</label>
                            </div>
                        </div>
                        <br />
                        <div class="ibox-content">
                            <div id="jstree1">
                                @{
                                    string st = string.Empty;
                                    st = TreeStructure.FolderTree(0, ViewBag.OpenFolderId);
                                }
                                @Html.Raw(st);
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="ibox-content">
                        <div id="divFolderDetail">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <link href="~/Content/plugins/jsTree/style.min.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/plugins/jsTree/jstree.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#SearchFolderName-error').hide();
            // PAGE RELATED SCRIPTS
            $('#jstree1').jstree({
                'core': {
                    'check_callback': true
                },
                'plugins': ['types', 'dnd'],
                'types': {
                    'default': {
                        'icon': 'fa fa-folder'
                    },
                    'doc': {
                        'icon': 'fa fa-file-word-o'
                    },
                    'docx': {
                        'icon': 'fa fa-file-word-o'
                    },
                    'html': {
                        'icon': 'fa fa-file-code-o'
                    },
                    'svg': {
                        'icon': 'fa fa-file-picture-o'
                    },
                    'css': {
                        'icon': 'fa fa-file-code-o'
                    },
                    'img': {
                        'icon': 'fa fa-file-image-o'
                    },
                    'png': {
                        'icon': 'fa fa-file-image-o'
                    },
                    'jpeg': {
                        'icon': 'fa fa-file-image-o'
                    },
                    'js': {
                        'icon': 'fa fa-file-text-o'
                    },
                    'pdf': {
                        'icon': 'fa fa-file-pdf-o'
                    },
                    'zip': {
                        'icon': 'fa fa-file-archive-o'
                    },
                    'xls': {
                        'icon': 'fa fa-file-excel-o'
                    },
                    'xlsx': {
                        'icon': 'fa fa-file-excel-o'
                    },
                    'ppt': {
                        'icon': 'fa fa-file-powerpoint-o'
                    }
                }
            });
            folderDetails(@ViewBag.OpenFolderId);
        });

        $("#btnSearchFolder").click(function () {
            if ($('#SearchFolderName').val() != '') {
                $('#SearchFolderName-error').hide();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("SearchFolder", "FolderAndFile")',
                    data: { FolderName: $('#SearchFolderName').val() },
                    success: function (data) {
                        var url = '@Url.Action("FolderTreeView", "FolderAndFile")';
                        if (data.success) {
                            //var url = '@Url.Action("FolderTreeView", "FolderAndFile")';
                            window.location.href = url + '?openFolderId=' + data.folderId;
                        } else {
                            window.location.href = url;
                        }
                    }
                });
            }
            else {
                $('#SearchFolderName-error').show();
            }
        });

        function folderDetails(id) {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("_FolderDetails", "FolderAndFile")',
                data: { folderId: id },
                success: function (data) {
                    $("#divFolderDetail").empty();
                    $("#divFolderDetail").html(data);
                    if (id === 0) {
                        $('.jstree-anchor').removeClass("jstree-clicked");
                    }
                }
            });
        }
    </script>
}

DocWare/Views/FolderAndFile/_AddNewChildLink.cshtml
@model LinkDocumentVM


@if (Model.LinkChildDocumentList.Count > 0)
{
    foreach (var child1 in Model.LinkChildDocumentList.Where(x => x.ParentId == Model.DocumentId).ToList())
    {
        var childDoc = Model.LinkChildDocumentList.Where(x => x.ParentId == child1.DocumentId).ToList();
        <tr id="p_@child1.DocumentId"  class="child_files" data-fileId="@child1.DocumentId">
            <td><i onclick="removeFrom(@child1.DocumentId,'@child1.DocumentType','@child1.Name')" class="fa fa-times-circle-o text-danger"></i></td>
            <td><span class="file-default @child1.DocumentType"></span> @child1.Name</td>
            <td>@child1.DocumentVersionOwner</td>
            <td id="td-@child1.DocumentId">@child1.OriginalLocation</td>
            <td>
                @if (childDoc.Any())
                {
                    <a class="parent-dd" onclick="showChild(@child1.DocumentId)">Is Parent <i class="fa fa-angle-down D_Arrow_@child1.DocumentId txt-black"></i></a>
                }
            </td>

        </tr>
        if (childDoc.Any())
        {
            <tr id="hide_table_@child1.DocumentId" class="hide_table">
                <td colspan="5">
                    <table width="100%" border="0">
                        <tbody>
                            @foreach (var child2 in childDoc)
                            {
                                <tr>
                                    <td width="6%"></td>
                                    <td><span class="file-default @child2.DocumentType"></span> @child2.Name</td>
                                    <td>@child2.DocumentVersionOwner</td>
                                    <td>@child2.OriginalLocation</td>
                                    <td>&nbsp;</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }

    }
}

DocWare/Views/FolderAndFile/_FolderFileComment.cshtml
@model List<FolderFileComments>

@if (Model.Count != 0)
{
    <div class="tabheading">
        <h3>
            <i class="fa tbl_icon @(Model.FirstOrDefault().DocumentType != "" ? Model.FirstOrDefault().DocumentType : "folder")"></i>
            
            @if (Model.FirstOrDefault().DocumentType != "")
            {
                <span style="cursor:pointer" onclick="PreviewDocumentByName( @Model.FirstOrDefault().DocVersionId)">@Model.FirstOrDefault().Name</span>
            }
            else
            {
                <span>@Model.FirstOrDefault().Name</span>
            }
        </h3>
        <p class="@(Model.FirstOrDefault().DocumentType != "" ? " visible" : " hidden ")">Click on file name to preview</p>
    </div>
    <!--  Comment List-->
    <div class="comment-list" id="FolderFileComments">
        @{ 
            var cmntNo = 0;
        }
        @foreach (var item in Model)
        {
            if (item.Comment != null && item.Comment != "")
            {
                cmntNo = cmntNo + 1;
                <div class="Timeline">
                    <div class="time_user">
                        @if (item.ImageName != null && item.ImageName != "")
                        {
                            <img class="img-circle" src="~/Uploads/ProfilePic/@item.ImageName" onerror="this.onerror=null;this.src='/Images/User1.png';" alt="@item.FullName" />
                        }
                        else
                        {
                            <img alt="Me" class="img-circle" src="~/Images/User1.png">
                        }
                    </div>
                    <div class="time_time">@item.FullName<br>@item.CommentDateTime</div>
                    <div class="clearfix"></div>
                    @*<p>@item.Comment</p>*@
                    <p class="fixheight" data-cn="@cmntNo" id="p_toggle_@cmntNo">@item.Comment
                      </p>
                    <span class="toggle viewMore view-comment" onClick="ReadMoreLess(this)" id="toggle_@cmntNo">more</span>

                </div>
            }
        }
    </div>
    if (Model.Count > 2)
    {
        @*<a href="javascript:void(0)" class="coment_a">view more comments...</a>*@
    }
    <!--End :  Comment List-->
    <div class="type_comment addfolderfilecomment">
        <input type="text" placeholder="type a comment"  id="txtComment"  onkeypress="return SaveCommentCtrlEnter(event);" />
        <i class="fa fa-location-arrow" onclick="SaveSentComment()"></i>
    </div>
}

<script>

    $(document).ready(function () {
        $('[id^="p_toggle_"]').each(function () {
            var ID = this.id;
            var Length = $("#" + ID).text().length;
            var cmno = $("#" + ID).attr("data-cn");

            if (Length <= 80) {
                $("#toggle_" + cmno).text("");
            } else {
                $("#toggle_" + cmno).text("more");
            }
        });
    });

    function ReadMoreLess(e) {

        var commentNo = e.id;
        var elem = $("#" + commentNo).text();
        if (elem == "more") {
            $("#" + commentNo).text("less");
            $("#p_" + commentNo).toggleClass("fixheight");

        } else {
            $("#" + commentNo).text("more");
            $("#p_" + commentNo).toggleClass("fixheight");
        }
    }    // End Of Function


</script>